version: '3.9'

services:
  db:
    image: mongo:6.0
    container_name: ${MONGO_DB_NAME}
    restart: always
    ports:
      - 2717:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    command: ['--auth']


volumes:
  mongo_data:
    external: false
